// LinkedIn Learning (linkedin.com/learning/<course>/<lesson>) site adapter.
//
// The lesson's caption files are plain WebVTT on dms.licdn.com, one per language,
// and the player preloads several of them (other languages, the next lessons) —
// so the file sniffer can't tell which one is playing. The page's own GraphQL
// "videos" query (the one the player runs for the lesson) lists them instead:
// videoPlayMetadata.transcripts = [{ locale, captionFile, isAutogenerated }].
// Only the human-made track(s) are offered: that one is the lesson's spoken
// language, and LinkedIn's auto-translations must not stand in for ours.
//
// If the query fails (signed out, a renamed query), the engine falls back to the
// caption video.js is drawing (.vjs-text-track-display, hidden by applyHideNative).

(function () {
  // The query id is a hash baked into LinkedIn's bundle; the player's own request
  // carries the current one. The constant is the one seen on 2026-10-05.
  const QUERY_FALLBACK = "videos.eb0cecfaa25dcd83d23769c32e492c1e";
  const slugs = () => {
    const m = location.pathname.match(/^\/learning\/([^/]+)\/([^/?#]+)/);
    return m ? { course: m[1], video: m[2] } : null;
  };
  const queryId = () => {
    let id = "";
    try { for (const e of performance.getEntriesByType("resource")) { const m = /queryId=(videos\.[0-9a-f]+)/.exec(e.name); if (m) id = m[1]; } } catch (e) {}
    return id || QUERY_FALLBACK;
  };
  const csrf = () => (document.cookie.match(/JSESSIONID="?([^";]+)/) || [])[1] || "";

  // One request per lesson: tracks and the board's description both come from it.
  let lessonP = null, lessonFor = "";
  function lesson() {
    const s = slugs();
    if (!s) return Promise.resolve(null);
    const key = s.course + "/" + s.video;
    if (lessonP && lessonFor === key) return lessonP;
    lessonFor = key;
    lessonP = (async () => {
      const url = `/learning-api/graphql?includeWebMetadata=true&variables=(courseSlug:${s.course},videoSlug:${s.video})&queryId=${queryId()}`;
      const r = await fetch(url, { credentials: "include", headers: { "csrf-token": csrf(), accept: "application/vnd.linkedin.normalized+json+2.1", "x-restli-protocol-version": "2.0.0" } });
      if (!r.ok) throw new Error("LinkedIn videos query " + r.status);
      const j = await r.json();
      for (const x of j.included || []) {
        const meta = x.presentationDerived && x.presentationDerived.videoPlay && x.presentationDerived.videoPlay.videoPlayMetadata;
        if (meta && x.slug === s.video) return { title: x.title || "", description: (x.descriptionV3 && x.descriptionV3.text) || "", transcripts: meta.transcripts || [] };
      }
      return null;
    })().catch((e) => { console.warn("[CopilotSubs] LinkedIn lesson query failed:", e); if (lessonFor === key) lessonP = null; return null; });
    return lessonP;
  }

  const adapter = {
    site: "linkedin",

    matches() { return location.hostname === "www.linkedin.com" && !!slugs(); },

    getVideoId() { const s = slugs(); return s ? s.course + "/" + s.video : ""; },

    getVideoEl() { return document.querySelector(".classroom-media-player video") || document.querySelector("video.vjs-tech") || document.querySelector("video"); },

    getPlayerContainer() {
      const v = adapter.getVideoEl();
      return document.querySelector(".media-player__player") || document.querySelector(".video-js") || (v && v.parentElement) || document.body;
    },

    async getCaptionTracks() {
      const l = await lesson();
      if (!l) return [];
      const human = l.transcripts.filter((t) => t.captionFile && !t.isAutogenerated);
      return human.map((t, i) => {
        const lang = (t.locale && t.locale.language) || "";
        return { languageCode: lang === "in" ? "id" : lang, name: lang, baseUrl: t.captionFile, kind: "", isDefault: i === 0 };
      });
    },

    // The caption file is CORS-open to linkedin.com; the worker re-fetch is the fallback.
    async fetchCues(url) {
      let text = "";
      try { const r = await fetch(url); if (r.ok) text = await r.text(); } catch (e) {}
      if (!text) { try { const r = await chrome.runtime.sendMessage({ type: "FETCH_SUBS", url }); text = (r && r.text) || ""; } catch (e) {} }
      return text && window.__copilotParseSubs ? window.__copilotParseSubs(text) : [];
    },

    readNativeText() {
      const el = document.querySelector(".vjs-text-track-display .vjs-text-track-cue");
      return el ? (el.innerText || el.textContent || "").replace(/\s+/g, " ").trim() : "";
    },

    // The lesson and its course for the board's identity line; the lesson's own description for the model.
    async getMeta() {
      const l = await lesson();
      const course = [...document.querySelectorAll("h1")].map((h) => (h.innerText || "").trim()).find((t) => t && !/^LinkedIn Learning$/i.test(t)) || ""; // the first h1 is the logo
      const lessonTitle = (l && l.title) || document.title.replace(/\s*\|\s*LinkedIn Learning\s*$/, "");
      return { site: "linkedin", url: location.href, title: lessonTitle, channel: course || "LinkedIn Learning", description: ((l && l.description) || "").slice(0, 1500) };
    },

    // The classroom moves between lessons by pushState, so the URL is watched.
    onNavigate(cb) {
      let last = location.pathname;
      window.addEventListener("popstate", cb);
      setInterval(() => { if (location.pathname !== last) { last = location.pathname; cb(); } }, 500);
    },
  };

  (window.__copilotAdapters = window.__copilotAdapters || []).push(adapter);
})();
